routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
'member' => 'MemberController',
'product' => 'ProductController',
'product_category' => 'ProductCategoryController',
'promo' => 'PromoController',
'member_category' => 'MemberCategoryController',
'transaksi' => 'TransaksiController',
]);

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    public function categoryRef()
    {
      return $this->belongsTo(MemberCategory::class, 'member_category_id');
    }
    public function pembeli()
    {
      return $this->hasMany(Transaksi::class, 'member_id');
    }
}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use App\Member;
use App\MemberCategory;
use Illuminate\Http\Request;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $category = Member::with('categoryRef')->get();
        return view('member.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = MemberCategory::all();
        return view('member.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $member = new Member;
       $member->member_category_id = $request->category;
       $member->full_name = $request->full_name;
       $member->dob = $request->dob;
       $member->address = $request->address;
       $member->gender = $request->gender;
       $barcode = str_replace("-","",$request->date_of_birth).substr(str_shuffle('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'),1,3);
       $member->barcode = $barcode;
       $member->save();
       return redirect()->route('member.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function show(Member $member)
    {
        $member = member::with('pembeli.categoryRef')->findorFail($member->id);
        return view('member.history', compact('member'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function edit(Member $member)
    {
        $category = MemberCategory::all();
        return view('member.edit', compact('category', 'member'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Member $member)
    {
       
       $member->member_category_id = $request->category;
       $member->full_name = $request->full_name;
       $member->dob = $request->dob;
       $member->address = $request->address;
       $member->gender = $request->gender;
       $barcode = str_replace("-","",$request->date_of_birth).substr(str_shuffle('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'),1,3);
       $member->barcode = $barcode;
       $member->save();
       return redirect()->route('member.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function destroy(Member $member)
    {
        $member->delete();
        return redirect()->route('member.index');
    }
}

resources/views/member/create.blade.php
@extends('layouts.template')

@section('content')

<div class="container">
<div class="x_panel">
    <div class="x_title">
      <div class="card shadow mb-4">
  <div class="card-header py-2">
     <h1 class="h3 mb-1 text-gray">Tambah kategori anggota</h1>

<!-- DataTales Example -->
<div class="card shadow mb-3">
  <div class="card-header py-2">

    <div class="card body">                           
    <form action="{{ route ('member.store') }}" method="post">
    @csrf 
    <form role="form">
        <div class="col-md-6">
            <div class="form-group">
                <label for="category">Nama</label>
                <select class="form-control" id="category" name="category">
                            <option>chose...</option>
                                @foreach ($category as $item)
                                <option value="{{ $item->id }}"> {{ $item->name }}</option>
                                @endforeach
                        </select>
            </div>
            <div class="form-group">
                <label for="full_name">Nama Lengkap</label>
                <input type="text" name="full_name" class="form-control" id="full_name" placeholder="Masukkan Nama Lengkap">
            </div>
            <div class="form-group">
                <label for="dob">Tanggal Lahir</label>
                <input type="date" name="dob" class="form-control" id="dob" placeholder="Masukkan Tanggal Lahir">
            </div>
            <div class="form-group">
                <label for="address">Alamat</label>
                <input type="text" name="address" class="form-control" id="address" placeholder="Masukkan Alamat">
            </div>
            <div class="form-group">
                <label class="mr-4" rows="1">Jenis Kelamin</label>
                                    <div class="form-group">
                                        <div class="custom-control custom-radio custom-control-inline">
                                        <input type="radio" name="gender" id="gender1" value="laki-laki" class="custom-control-input" >
                                        <label class="custom-control-label" for="gender1">Laki-Laki</label>
                                        </div>
                                    </div>

                                    <div class="custom-control custom-radio custom-control-inline">
                                        <input type="radio" name="gender" id="gender2" value="perempuan" class="custom-control-input" >
                                        <label class="custom-control-label" for="gender2">Perempuan</label>
                                        </div>
                                    </div>
            </div>
            

            <button type="submit" class="btn btn-danger">Simpan</button>
            <a href="/member" class="btn btn-warning">Kembali</a>
    </form>
    </div> 
    </div> 
    </div>
    </div>                                 
@endsection

resources/views/member/edit.blade.php
@extends('layouts.template')

@section('content')

<div class="container">
<div class="x_panel">
    <div class="x_title">
      <div class="card shadow mb-4">
  <div class="card-header py-2">
     <h1 class="h3 mb-1 text-gray">Ubah Anggota</h1>

<!-- DataTales Example -->
<div class="card shadow mb-3">
  <div class="card-header py-2">

    <div class="card body">                           
    <form action="{{ route ('member.update', $member->id) }}" method="post">
    @csrf 
    @method('put')
    <form role="form">
        <div class="col-md-6">
            <div class="form-group">
                <label for="category">Nama</label>
                <select class="form-control" id="category" name="category">
                            <option>chose...</option>
                                @foreach ($category as $item)
                                <option value="{{ $item->id }}" > {{ $item->name }}</option>
                                @endforeach
                        </select>
            </div>
            <div class="form-group">
                <label for="full_name">Nama Lengkap</label>
                <input type="text" name="full_name" class="form-control" id="full_name" placeholder="Masukkan Nama Lengkap" value="{{$member->full_name}}">
            </div>
            <div class="form-group">
                <label for="dob">Tanggal Lahir</label>
                <input type="date" name="dob" class="form-control" id="dob" placeholder="Masukkan Tanggal Lahir" value="{{$member->dob}}">
            </div>
            <div class="form-group">
                <label for="address">Alamat</label>
                <input type="text" name="address" class="form-control" id="address" placeholder="Masukkan Alamat" value="{{$member->address}}">
            </div>
            <div class="form-group">
                <label class="mr-4">Jenis Kelamin</label>
                                    <div class="form-group">
                                        <div class="custom-control custom-radio custom-control-inline">
                                        <input type="radio" name="gender" id="gender1" value="laki-laki" class="custom-control-input">
                                        <label class="custom-control-label" for="gender1">Laki-Laki</label>
                                        </div>
                                    </div>

                                    <div class="custom-control custom-radio custom-control-inline">
                                        <input type="radio" name="gender" id="gender2" value="perempuan" class="custom-control-input" >
                                        <label class="custom-control-label" for="gender2">Perempuan</label>
                                        </div>
                                    </div>
            </div>
            <div class="form-group">
                <label for="barcode">Barcode</label>
                <input type="text" name="barcode" class="form-control" id="barcode" placeholder="Masukkan Nama Barang" value="{{$member->barcode}}">
            </div>

            <button type="submit" class="btn btn-danger">Simpan</button>
            <a href="/member" class="btn btn-warning">Kembali</a>
    </form>
    </div> 
    </div> 
    </div>
    </div>                                 
@endsection

resources/views/member/history.blade.php
@extends('layouts.template')

@section('content')


     
  <!-- Begin Page Content -->
  <div class="container-fluid">

<!-- Page Heading -->
<div class="card shadow mb-4">
  <div class="card-header py-2">
     <h1 class="h3 mb-1 text-gray">Detail Anggota</h1>

<!-- DataTales Example -->
<div class="card shadow mb-3">
  <div class="card-header py-2">
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr style="text-align: center;">
            <th>No</th>
            <th>No Transaksi</th>
            <th>Nama lengkap</th>
            <th>Nama Product</th>
            <th>Kuantitas</th>
            <th>Diskon</th>
            <th>Total</th>
          </tr>
        </thead>
        
        <tbody>
              @foreach ($member->pembeli as $i => $item)
              <tr style="text-align: center;">
                  <td>{{ $i+1 }}</td>
                  <td>{{ $item->trx_number }}</td>
                  <td>{{ $item->categRef->full_name }}</td>
                  <td>{{ $item->categoryRef->name }}</td>
                  <td>{{ $item->quantity }}</td>
                  <td>{{ $item->discount }}</td>
                  <td>{{ $item->total }}</td>
                  <td>
                </td>
              </tr>
              @endforeach
              </tbody>  
        
      </table>
    </div>
  </div>
</div>
@endsection

resources/views/member/index.blade.php
@extends('layouts.template')

@section('content')


     
  <!-- Begin Page Content -->
  <div class="container-fluid">

<!-- Page Heading -->
<div class="card shadow mb-4">
  <div class="card-header py-2">
     <h1 class="h3 mb-1 text-gray">Anggota</h1>

<!-- DataTales Example -->
<div class="card shadow mb-3">
  <div class="card-header py-2">
      <li>
        <a href="{{ route('member.create') }}">
          <button type="button" class="btn btn-primary btn-sm">Tambah</button>
        </a>
      </li>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr style="text-align: center;">
            <th>No</th>
            <th>Kategori Anggota</th>
            <th>Nama lengkap</th>
            <th>Tanggal Lahir</th>
            <th>Alamat</th>
            <th>Gender</th>
            <th>Barcode</th>
            <th>Pilihan</th>
          </tr>
        </thead>
        
        <tbody>
              @foreach ($category as $i => $item)
              <tr style="text-align: center;">
                  <td>{{ $i+1 }}</td>
                  <td>{{ $item->categoryRef->name }}</td>
                  <td>{{ $item->full_name }}</td>
                  <td>{{ $item->dob }}</td>
                  <td>{{ $item->address }}</td>
                  <td>{{ $item->gender }}</td>
                  <td>{{ $item->barcode }}</td>
                  <td>
                  <form action="{{ route('member.destroy',$item->id) }}" 
                    method="post">
                    <a href="{{ route('member.edit',$item->id) }}">
                      <button type="button" class="btn btn-success">Ubah</button>
                    </a>
                    @csrf 
                    @method('delete')
                      <button type="submit" class="btn btn-warning" 
                      onclick="return confirm('Yakin Nih Dihapus ?')"><i class="fas fa-trash"></i></button>
                      <a href="{{ route('member.show',$item->id) }}" class="btn btn-info btn-circle">
                <i class="fas fa-list"></i>
               </a>
                    </form>
                </td>
              </tr>
              @endforeach
              </tbody>  
        
      </table>
    </div>
  </div>
</div>
@endsection